[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
reqwest = "0.11"
serde = {version = "1.0", features = ["derive"]}
tokio = {version = "1", features = ["full"]}